config/routes.rb
Rails.application.routes.draw do
  resources :manga
  resources :series
  resources :categories
  resources :authors
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'home/index'

  root to: 'home#index'
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :set_series, only: %i[ show edit update destroy ]

  # GET /series or /series.json
  def index
    @series = Series.all
  end

  # GET /series/1 or /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # GET /series/1/edit
  def edit
  end

  # POST /series or /series.json
  def create
    @series = Series.new(series_params)

    respond_to do |format|
      if @series.save
        format.html { redirect_to series_url(@series), notice: "Series was successfully created." }
        format.json { render :show, status: :created, location: @series }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /series/1 or /series/1.json
  def update
    respond_to do |format|
      if @series.update(series_params)
        format.html { redirect_to series_url(@series), notice: "Series was successfully updated." }
        format.json { render :show, status: :ok, location: @series }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1 or /series/1.json
  def destroy
    @series.destroy

    respond_to do |format|
      format.html { redirect_to series_index_url, notice: "Series was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def series_params
      params.require(:series).permit(:title, :category_id, :author_id, :download_status, :series_status, :total_volume, :cover_image_url)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
end

app/views/series/_form.html.erb
<%= form_with(model: series, local: true) do |form| %>
  <% if series.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(series.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% series.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :author_id %>
    <%= form.text_field :author_id %>
  </div>

  <div class="field">
    <%= form.label :download_status %>
    <%= form.check_box :download_status %>
  </div>

  <div class="field">
    <%= form.label :series_status %>
    <%= form.check_box :series_status %>
  </div>

  <div class="field">
    <%= form.label :total_volume %>
    <%= form.number_field :total_volume %>
  </div>

  <div class="field">
    <%= form.label :cover_image_url %>
    <%= form.text_field :cover_image_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/series/edit.html.erb
<h1>Editing Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Show', @series %> |
<%= link_to 'Back', series_index_path %>

app/views/series/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Series</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Author</th>
      <th>Download status</th>
      <th>Series status</th>
      <th>Total volume</th>
      <th>Cover image url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @series.each do |series| %>
      <tr>
        <td><%= series.title %></td>
        <td><%= series.category %></td>
        <td><%= series.author %></td>
        <td><%= series.download_status %></td>
        <td><%= series.series_status %></td>
        <td><%= series.total_volume %></td>
        <td><%= series.cover_image_url %></td>
        <td><%= link_to 'Show', series %></td>
        <td><%= link_to 'Edit', edit_series_path(series) %></td>
        <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Series', new_series_path %>

app/views/series/new.html.erb
<h1>New Series</h1>

<%= render 'form', series: @series %>

<%= link_to 'Back', series_index_path %>

app/views/series/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @series.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @series.category %>
</p>

<p>
  <strong>Author:</strong>
  <%= @series.author %>
</p>

<p>
  <strong>Download status:</strong>
  <%= @series.download_status %>
</p>

<p>
  <strong>Series status:</strong>
  <%= @series.series_status %>
</p>

<p>
  <strong>Total volume:</strong>
  <%= @series.total_volume %>
</p>

<p>
  <strong>Cover image url:</strong>
  <%= @series.cover_image_url %>
</p>

<%= link_to 'Edit', edit_series_path(@series) %> |
<%= link_to 'Back', series_index_path %>